# Generated by Django 3.1.5 on 2021-02-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FK', 'fix kit'), ('L', 'lipstick'), ('LP', 'lip plumper'), ('EP', 'eyeshadow primer'), ('E', 'eyeliner'), ('CC', 'complete concealer'), ('FO', 'face oil'), ('FP', 'face primer'), ('BC', 'brow colour'), ('SG', 'shaping gel'), ('PP', 'pomade pencil')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'sale'), ('D', 'Discount')], default='PP', max_length=1),
            preserve_default=False,
        ),
    ]
