# Generated by Django 3.1.5 on 2021-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210216_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='SG', max_length=255),
            preserve_default=False,
        ),
    ]
