# Generated by Django 3.1.5 on 2021-02-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_bottom',
            field=models.CharField(default='S', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='reviews',
            field=models.CharField(default='E', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
