# Generated by Django 3.1.5 on 2021-02-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210217_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_bottom',
            field=models.TextField(null=True, verbose_name='Description_bottom'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviews',
            field=models.TextField(null=True, verbose_name='Reviews'),
        ),
    ]
