# Generated by Django 3.1.5 on 2021-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210217_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('position', models.CharField(choices=[('C', 'client'), ('BE', 'beauty expert')], max_length=2)),
                ('user_comment', models.TextField(max_length=2000)),
            ],
        ),
    ]
