# Generated by Django 3.1.5 on 2021-02-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='user_comment',
            new_name='comment',
        ),
    ]
