# Generated by Django 3.1.5 on 2021-02-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210217_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
            preserve_default=False,
        ),
    ]
