# Generated by Django 3.1.5 on 2021-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(choices=[('client', 'client'), ('beauty expert', 'beauty expert')], max_length=50),
        ),
    ]
