# Generated by Django 3.1.5 on 2021-02-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210221_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='title',
            new_name='name',
        ),
    ]
